# All relative paths are relative to this config file.
WatchDir    = "."
BuildCmd    = "go install"
BuildCmdDir = "."
BuildFile   = "~/go/bin/builderator"
StatusFile  = "/tmp/buildstatus-builderator"
